CREATE database acme;
CREATE TABLE FUNCIONARIO(
ID INT NOT NULL PRIMARY KEY auto_increment,
NOME VARCHAR(250),
SALARIO double,
MATRICULA VARCHAR(100),
EMAIL VARCHAR(200),
DEPARTAMENTO VARCHAR(200), 
CARGO VARCHAR(200),
TELEFONE VARCHAR(200)
);
CREATE TABLE DEPARTAMENTO(
IDDP VARCHAR(200) NOT NULL PRIMARY KEY auto_increment,
NOME VARCHAR(200),
NUMERO VARCHAR(200)
);
CREATE TABLE DEPENDENTE(
ID INT NOT NULL PRIMARY KEY auto_increment,
NOME VARCHAR(250),
MATRICULA VARCHAR(200),
FUNCIONARIO VARCHAR(200)
);
select * from funcionario;
select * from departamento;
select * from dependente